#pragma once

#include <mln/style/layer_impl.hpp>
#include <mln/style/layers/slope_shading_layer.hpp>
#include <mln/style/layers/slope_shading_layer_properties.hpp>

namespace mln {
namespace style {

// DuckMaps fork only, task 2.6. Slope/aspect area fill computed per-fragment from the terrain
// DEM, drawn over RenderTerrain's own mesh - see container/server/app/map/assets/contours3d.js
// (the web reference this ports) and terrain_contour_layer_impl.hpp, whose shape this mirrors -
// no source, no bucket, modelled on BackgroundLayer::Impl's shape.
//
// stringifyLayout MUST be declared here (Layer::Impl declares it pure virtual - omitting the
// declaration makes this class abstract and uninstantiable) but must NOT also be DEFINED in
// slope_shading_layer_impl.cpp: slope_shading_layer.cpp (generated by generate-style-code.mjs's
// layer.cpp.ejs) already provides the one out-of-line definition, unconditionally, for every
// layer type with no non-visibility layout properties (an empty body, since there is nothing to
// stringify) - see that ejs template's own `<% if (layoutProperties.length) %>` branch. A second
// definition in this class's own .cpp would be an ODR violation: terrain_contour_layer_impl.cpp
// has exactly that duplicate today, harmless only because optimized/LTO builds happen to fold
// two byte-identical empty bodies together - a plain (non-LTO) link of the same sources fails
// outright with "duplicate symbol ... stringifyLayout", which is how this was found
// (development/app-bench/journal.md, task 2.6). Not fixed on TerrainContourLayer::Impl itself:
// out of scope for this task, flagged separately.
class SlopeShadingLayer::Impl : public Layer::Impl {
public:
    using Layer::Impl::Impl;
    Impl(const Impl&);

    bool hasLayoutDifference(const Layer::Impl&) const override;
    void stringifyLayout(rapidjson::Writer<rapidjson::StringBuffer>&) const override;

public:
    SlopeShadingPaintProperties::Transitionable paint;

    DECLARE_LAYER_TYPE_INFO;
};

} // namespace style
} // namespace mln
